In [1]:
import pandas as pd
import numpy as np

### Load table

In [2]:
class pdbTable:
    def __init__( self , file_addr):
        self.df = pd.read_csv(file_addr,sep=",",skiprows=[0],header=None)
        f = open(file_addr,'r')
        self.table_name = f.read(1)
        self.vals = self.df.values
        
    def getProb(self,var_list):
        index_array= np.empty((0))
        for i in range(len(var_list)):
            a = np.where(t.vals[:,i]==var_list[i])
            if len(index_array)==0:
                index_array = a
            else:
                index_array = np.intersect1d(a,index_array)
        return self.vals[index_array[0]][-1]

In [3]:
t = pdbTable('/home/jingxi/Documents/CS267/pdb/db/table_file_3.txt')
print(t.table_name)
print(t.vals)
print(t.getProb([1,2]))

R
[[0.  0.  0.8]
 [0.  1.  0.4]
 [0.  2.  0.5]
 [1.  2.  0.6]
 [2.  2.  0.9]]
0.6


### Parse query file (union of conjunctive queries) into individual conjunctive query

In [4]:
def parse_query(query_addr):
    df_val = pd.read_csv(query_addr,header=None,sep='\n').values
    q=[]
    for i in range(len(df_val)):
        s = str(df_val[i])
        s = s.replace('|','')
        s = s.replace('\'','')
        s = s.replace(' ','')
        q.append(s)
    return q

In [5]:
ucq = parse_query('./db/query.txt')
print(ucq)

['[R(x1),S(x1,y1)]', '[S(x2,y2),T(x2)]']


### parse conjunctive query into a table with each corresponding variable

In [6]:
def parse_cq(q_str):
    i = 0
    #table map
    # TABLE NAME:[VAR1,VAR2,...]
    table={}
    current_table = ''
    var=''
    while(i<len(q_str)):
        if q_str[i].isupper():
            table[q_str[i]] = []
            current_table = q_str[i]
        else:
            if((q_str[i] == ',' or q_str[i] == ')') and var):
                table[current_table].append(var)
                var='' 
            elif (q_str[i] not in "(),"):
                var+= q_str[i]
        i = i+1
    return table

In [7]:
for cq in ucq:
    t = parse_cq(cq)
    print(t)

{'R': ['[x1'], 'S': ['x1', 'y1']}
{'S': ['[x2', 'y2'], 'T': ['x2']}
